// <auto-generated />
using System;
using IdentityProviderInfrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdentityProviderInfrastructure.Migrations
{
    [DbContext(typeof(IdentityProviderDbContext))]
    partial class IdentityProviderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-preview.8.20407.4");

            modelBuilder.Entity("IdentityProviderCore.Entities.EnterpriseUser", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EntityId")
                        .IsClustered(false);

                    b.HasIndex("EntityId", "UserId")
                        .IsClustered(false);

                    b.ToTable("EnterpriseUsers");

                    b.HasData(
                        new
                        {
                            EntityId = new Guid("86019bf7-27ce-4f9f-9b6c-e2f08608e063"),
                            Id = 1,
                            OrganizationName = "Org1",
                            UserId = new Guid("4bd23529-22a1-4802-992d-d8b12c3dfc5f")
                        },
                        new
                        {
                            EntityId = new Guid("d027528c-77d8-4f1b-b3a6-79ee911f9760"),
                            Id = 2,
                            OrganizationName = "Org2",
                            UserId = new Guid("5472e4ad-b07c-4bc4-a747-8784fedcf46d")
                        },
                        new
                        {
                            EntityId = new Guid("368e9465-da5c-41b0-895b-adcd85a6ffb8"),
                            Id = 3,
                            OrganizationName = "Org3",
                            UserId = new Guid("6427fbbb-4464-459d-83f5-9333ae9ae475")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
